const DEFAULT_MAX_SIZE = 500;
const DEFAULT_EXPIRE_AFTER_WRITE = 0; // 0 = never
const DEFAULT_EXPIRE_AFTER_ACCESS = 0; // 0 = never
const DEFAULT_REFRESH_AFTER_WRITE = 0; // 0 = disabled

module.exports = {
  DEFAULT_MAX_SIZE,
  DEFAULT_EXPIRE_AFTER_WRITE,
  DEFAULT_EXPIRE_AFTER_ACCESS,
  DEFAULT_REFRESH_AFTER_WRITE,
};
